ALTER TABLE businesses ADD COLUMN account_state TEXT NOT NULL DEFAULT 'active' CHECK (account_state IN ('active','deletion_pending','deleted','suspended'));
ALTER TABLE businesses ADD COLUMN deletion_requested_at TEXT;
ALTER TABLE businesses ADD COLUMN deletion_confirmation_expires_at TEXT;
ALTER TABLE businesses ADD COLUMN deletion_confirmed_at TEXT;
ALTER TABLE businesses ADD COLUMN deleted_at TEXT;
ALTER TABLE businesses ADD COLUMN terms_version TEXT;
ALTER TABLE businesses ADD COLUMN privacy_version TEXT;
ALTER TABLE businesses ADD COLUMN legal_notice_shown_at TEXT;
ALTER TABLE brand_profiles ADD COLUMN business_name TEXT;
ALTER TABLE brand_profiles ADD COLUMN logo_enabled INTEGER NOT NULL DEFAULT 0 CHECK (logo_enabled IN (0,1));
ALTER TABLE brand_profiles ADD COLUMN logo_position TEXT NOT NULL DEFAULT 'bottom_right' CHECK (logo_position IN ('top_left','top_right','bottom_left','bottom_right'));
ALTER TABLE brand_profiles ADD COLUMN setup_state TEXT NOT NULL DEFAULT 'none' CHECK (setup_state IN ('none','awaiting_logo','awaiting_business_name','awaiting_primary_color','awaiting_background_style','awaiting_logo_enabled','complete'));
ALTER TABLE image_jobs ADD COLUMN original_expires_at TEXT;
ALTER TABLE image_jobs ADD COLUMN generated_expires_at TEXT;
ALTER TABLE image_jobs ADD COLUMN blocked_expires_at TEXT;
CREATE TABLE deleted_identity_markers (identity_hash TEXT PRIMARY KEY, created_at TEXT NOT NULL);
CREATE TABLE rate_limit_events (id TEXT PRIMARY KEY, business_id TEXT NOT NULL REFERENCES businesses(id), kind TEXT NOT NULL, whatsapp_message_id TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(kind,whatsapp_message_id));
CREATE INDEX rate_limit_window ON rate_limit_events(business_id,kind,created_at);
CREATE TABLE brand_asset_jobs (id TEXT PRIMARY KEY, business_id TEXT NOT NULL REFERENCES businesses(id), whatsapp_message_id TEXT NOT NULL UNIQUE, media_id TEXT NOT NULL, mime_type TEXT NOT NULL, media_sha256 TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','complete','rejected')), brand_r2_key TEXT, created_at TEXT NOT NULL);
CREATE INDEX image_jobs_expiry ON image_jobs(original_expires_at,generated_expires_at,blocked_expires_at);
